src/Entity/Session.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Le label est obligatoire')]
    private string $label;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false, onDelete: "CASCADE")]
    private ?User $user = null;

    #[ORM\Column(type: 'integer')]
    #[Assert\Positive(message: 'La durée doit être positive')]
    private int $slotDuration;

    #[ORM\Column(type: 'integer')]
    #[Assert\PositiveOrZero(message: 'L\'intervalle doit être positif ou nul')]
    private int $slotInterval;

    #[ORM\OneToMany(mappedBy: 'session', targetEntity: DateSession::class)]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private Collection $dates;

    public function __construct()
    {
        $this->dates = new ArrayCollection();
        $this->slotDuration = 15;        // 20 minutes par défaut
        $this->slotInterval = 0;         // pas d'intervalle par défaut
        $this->label = '';               // label vide par défaut
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;
        return $this;
    }

    public function getSlotDuration(): int
    {
        return $this->slotDuration;
    }

    public function setSlotDuration(int $slotDuration): self
    {
        $this->slotDuration = $slotDuration;
        $this->recalculateAllDateSessionSlots();
        return $this;
    }

    public function getSlotInterval(): int
    {
        return $this->slotInterval;
    }

    public function setSlotInterval(int $slotInterval): self
    {
        $this->slotInterval = $slotInterval;
        $this->recalculateAllDateSessionSlots();
        return $this;
    }

    /**
     * @return Collection<int, DateSession>
     */
    public function getDates(): Collection
    {
        return $this->dates;
    }

    public function addDate(DateSession $date): self
    {
        if (!$this->dates->contains($date)) {
            $this->dates->add($date);
            $date->setSession($this);
        }
        return $this;
    }

    public function removeDate(DateSession $date): self
    {
        if ($this->dates->removeElement($date)) {
            if ($date->getSession() === $this) {
                $date->setSession(null);
            }
        }
        return $this;
    }

    public function __toString(): string
    {
        return sprintf(
            '%s (durée: %d min, intervalle: %d min)',
            $this->label,
            $this->slotDuration,
            $this->slotInterval
        );
    }

    /**
     * Recalcule les créneaux pour toutes les dates de session
     */
    private function recalculateAllDateSessionSlots(): void
    {
        foreach ($this->dates as $dateSession) {
            $dateSession->recalculateSlots();
        }
    }

    /**
     * Calcule le nombre total de créneaux disponibles pour cette session
     */
    public function getAvailableSlots(): array
    {
        $total = 0;
        $available = 0;

        foreach ($this->dates as $dateSession) {
            foreach ($dateSession->getSlots() as $slot) {
                $total++;
                if (!$slot->getIsBooked()) {
                    $available++;
                }
            }
        }

        return [
            'total' => $total,
            'available' => $available
        ];
    }
}

src/Entity/Slots.php
<?php

namespace App\Entity;

use App\Repository\SlotsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Reservations;

#[ORM\Entity(repositoryClass: SlotsRepository::class)]
class Slots
{
  #[ORM\Id]
  #[ORM\GeneratedValue]
  #[ORM\Column]
  private ?int $id = null;

  #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
  private ?\DateTimeImmutable $dateTime = null;

  #[ORM\Column(length: 255)]
  private ?string $available = 'yes';

  #[ORM\OneToOne(mappedBy: 'slot', targetEntity: Reservations::class)]
  private ?Reservations $reservation = null;

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getDateTime(): ?\DateTimeImmutable
  {
    return $this->dateTime;
  }

  public function setDateTime(\DateTimeImmutable $dateTime): static
  {
    $this->dateTime = $dateTime;

    return $this;
  }

  public function getAvailable(): ?string
  {
    return $this->available;
  }

  public function setAvailable(string $available): static
  {
    $this->available = $available;

    return $this;
  }

  // Calcul heure de fin de rendez-vous (20 minutes) à partir de l'heure de début
  public function getEndTime(): ?\DateTimeImmutable
  {
    return $this->dateTime->modify('+20 minutes');
  }

  public function getReservation(): ?Reservations
  {
    return $this->reservation;
  }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Le prénom est obligatoire')]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Le nom est obligatoire')]
    private ?string $lastName = null;

    #[ORM\Column(length: 180)]
    #[Assert\Email(message: 'L\'email {{ value }} n\'est pas valide')]
    #[Assert\NotBlank(message: 'L\'email est obligatoire')]
    private ?string $email = null;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Le mot de passe est obligatoire', groups: ['create'])]
    #[Assert\Length(
        min: 8,
        minMessage: 'Le mot de passe doit contenir au moins {{ limit }} caractères',
        groups: ['create', 'password_update']
    )]
    #[Assert\Regex(
        pattern: '/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d).+$/',
        message: 'Le mot de passe doit contenir au moins une majuscule, une minuscule et un chiffre',
        groups: ['create', 'password_update']
    )]
    private ?string $password = null;

    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\Length(
        max: 50,
        maxMessage: 'Le code public ne peut pas dépasser {{ limit }} caractères'
    )]
    private ?string $publicCode = null;

    #[ORM\OneToMany(
        mappedBy: 'user',
        targetEntity: Session::class,
        cascade: ['remove'],
        orphanRemoval: true
    )]
    private Collection $sessions;

    #[ORM\OneToMany(
        mappedBy: 'user',
        targetEntity: Eleve::class,
        cascade: ['persist', 'remove'],
        orphanRemoval: true
    )]
    private Collection $eleves;

    #[ORM\OneToMany(
        mappedBy: 'user',
        targetEntity: EleveImport::class,
        cascade: ['remove'],
        orphanRemoval: true
    )]
    private Collection $eleveImports;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
        $this->eleves = new ArrayCollection();
        $this->eleveImports = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;
        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;
        return $this;
    }

    public function getFullName(): string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;
        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;
        return $this;
    }

    public function getRoles(): array
    {
        return array_unique($this->roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }

    public function getPublicCode(): ?string
    {
        return $this->publicCode;
    }

    public function setPublicCode(?string $publicCode): self
    {
        $this->publicCode = $publicCode;
        return $this;
    }

    public function eraseCredentials(): void
    {
        // Si vous stockez des données temporaires sensibles sur l'utilisateur, effacez-les ici
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->setUser($this);
        }
        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->removeElement($session)) {
            // set the owning side to null (unless already changed)
            if ($session->getUser() === $this) {
                $session->setUser(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection<int, Eleve>
     */
    public function getEleves(): Collection
    {
        return $this->eleves;
    }

    public function addEleve(Eleve $eleve): self
    {
        if (!$this->eleves->contains($eleve)) {
            $this->eleves->add($eleve);
            $eleve->setUser($this);
        }
        return $this;
    }

    public function removeEleve(Eleve $eleve): self
    {
        if ($this->eleves->removeElement($eleve)) {
            // set the owning side to null (unless already changed)
            if ($eleve->getUser() === $this) {
                $eleve->setUser(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection<int, EleveImport>
     */
    public function getEleveImports(): Collection
    {
        return $this->eleveImports;
    }

    public function addEleveImport(EleveImport $eleveImport): self
    {
        if (!$this->eleveImports->contains($eleveImport)) {
            $this->eleveImports[] = $eleveImport;
            $eleveImport->setUser($this);
        }
        return $this;
    }

    public function removeEleveImport(EleveImport $eleveImport): self
    {
        if ($this->eleveImports->removeElement($eleveImport)) {
            if ($eleveImport->getUser() === $this) {
                $eleveImport->setUser(null);
            }
        }
        return $this;
    }
    public function __toString(): string
    {
        return (string) $this->email;
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Entity\DateSession;
use App\Entity\Eleve;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SessionController extends AbstractController
{

    #[Route('/sessions', name: 'session.index')]
    public function index(EntityManagerInterface $em): Response
    {
        $sessions = $em->getRepository(Session::class)->findAll();
        if (empty($sessions)) {
            $this->addFlash('info', 'Aucune session programmée pour le moment.');
        }
        return $this->render('session/index.html.twig', [
            'sessions' => $sessions,
        ]);
    }

    #[Route('/sessions/session-{id}/{filter}', name: 'session.show', defaults: ['filter' => 'all'])]
    public function all_slots_show(int $id, string $filter, EntityManagerInterface $em): Response
    {
        $sessionById = $em->getRepository(Session::class)->find($id);
        if (!$sessionById) {
            throw $this->createNotFoundException('Session non trouvée');
        }

        $dateSessionBySessionId = $em->getRepository(DateSession::class)->findBy(['session' => $sessionById]);
        if (empty($dateSessionBySessionId)) {
            $this->addFlash('warning', 'Aucune date programmée pour cette session');
        }

        $eleves = $em->getRepository(Eleve::class)->findAll();
        if (empty($eleves)) {
            $this->addFlash('warning', 'La liste des élèves n\'est pas renseignée.');
        }

        return $this->render('session/all_slots.html.twig', [
            'sessionId' => $sessionById,
            'dateSessions' => $dateSessionBySessionId,
            'eleves' => $eleves,
            'filter' => $filter,
        ]);
    }
}

templates/session/_session-table.html.twig
{# Tableau des créneaux #}
<table
  class="table table-sm md:table-md lg:table-lg table-zebra">
  <thead>
    <tr>
      <th>
        Horaire
      </th>
      {% if filter == 'all' %}
        {% set bookedSlots = dateSession.slots|filter(slot => slot.isBooked)|length %}
        {% if bookedSlots > 0 %}
          <th>
            Élève
          </th>
        {% else %}
          <th></th>
        {% endif %}
      {% endif %}
      <th>
        Action
      </th>
    </tr>
  </thead>

  <tbody>
    {% for slot in dateSession.slots %}
      <tr>
        <td
          class="font-medium">
          <div
            class="flex items-center gap-2">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 text-primary"
              fill="none"
              viewbox="0 0 24 24"
              stroke="currentColor">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>
            </svg>
            {{ slot.startTime|date('H:i') }}
            -
            {{ slot.endTime|date('H:i') }}
          </div>
        </td>
        {% if filter == 'all' %}
          <td
            class="font-medium">
            {{ slot.eleve.fullName|default('') }}
          </td>
        {% endif %}
        <td>
          {% if not slot.isBooked %}
            <button
              class="btn btn-success btn-md lg:btn-lg gap-2 transition-transform duration-200"
              onclick="openSignupModal('modal_{{ slot.id }}')">
              S'inscrire
            </button>

            {% include 'session/_signup_modal.html.twig' with {
              'slot': slot,
              'dateSession': dateSession,
              'eleves': eleves
            } only %}

          {% else %}
            <button
              class="btn btn-md lg:btn-lg btn-disabled"
              tabindex="-1"
              role="button"
              aria-disabled="true">
              Réservé
            </button>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

templates/session/_signup_modal.html.twig
{# Modal centrée, fond sombre #}

<dialog
  id="modal_{{ slot.id }}"
  class="modal">
  <div
    class="modal-box max-w-md flex flex-col justify-center items-center bg-base-100 shadow-lg">

    <h3
      class="badge badge-secondary badge-md md:badge-xl mb-4">


      {{ dateSession.session.label }}
    </h3>
    <p
      class="py-4">
      Voulez-vous réserver le créneau du
      {{ dateSession.date|date('d/m/Y') }}
      de
      {{ slot.startTime|date('H:i') }}
      à
      {{ slot.endTime|date('H:i') }}
      ?
    </p>
    <form
      action="{{ path('slot_reservation', {'id': slot.id}) }}" method="POST"
      class="w-full max-w-md mx-auto">
      <select
        name="eleve"
        class="select select-bordered w-full validator"
        required>
        <option
          disabled
          selected
          value="">
          Choisir un élève :
        </option>
        {% for eleve in eleves %}
          <option
            value="{{ eleve.id }}">
            {{ eleve.fullName }}
          </option>
        {% endfor %}
      </select>
      <p
        class="validator-hint">
        obligatoire
      </p>
      <div
        class="modal-action flex justify-center gap-4 mt-6">
        <button
          type="button"
          class="btn btn-error"
          onclick="document.getElementById('modal_{{ slot.id }}').close()">
          Annuler
        </button>
        <button
          type="submit"
          class="btn btn-success">
          Confirmer
        </button>
      </div>
    </form>
  </div>
</dialog>

templates/session/all_slots.html.twig
{% extends 'base.html.twig' %}

{# Titre dynamique en fonction du filtre #}
{% if filter == 'all' %}
  {% set page_title = "Tous les créneaux | Réserva'Classe" %}
  {% set page_title_h1 = "Tous les créneaux" %}
{% elseif filter == 'booked' %}
  {% set page_title = "Les créneaux réservés | Réserva'Classe" %}
  {% set page_title_h1 = "Les créneaux réservés" %}
{% else %}
  {% set page_title = "Les créneaux disponibles | Réserva'Classe" %}
  {% set page_title_h1 = "Les créneaux disponibles" %}
{% endif %}

{% block title %}
  {{ page_title }}
{% endblock %}

{% block title_h1 %}
  {{ page_title_h1 }}
{% endblock %}

{% block session_label %}
  <div
    class="badge badge-sm md:badge-xl badge-neutral mb-2">
    {{ sessionId.label }}
  </div>
{% endblock %}

{% block body %}

  <div
    class="container p-2 md:p-4">


    {# Tabs avec role="tablist" #}
    <div
      class="relative">
      <div
        role="tablist"
        class="tabs tabs-border mb-4 flex-nowrap overflow-x-auto">
        {% for dateSession in dateSessions %}
          <a
            role="tab"
            class="tab
                                                                                                                              {{ loop.first ? 'tab-active' : '' }}
                                                                                                                              flex-nowrap"
            onclick="openTab({{ loop.index }})">
            <span
              class="flex items-center gap-2">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-5 w-5"
                fill="none"
                viewbox="0 0 24 24"
                stroke="currentColor">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>
              </svg>
              {{ dateSession.date|date('d/m/Y') }}
            </span>
            {% if filter in ['free', 'all'] %}
              {% set availableSlots = dateSession.slots|filter(slot => not slot.isBooked) %}
              {% if availableSlots|length > 0 %}
                <span
                  class="badge badge-success badge-xs font-semibold ml-2 tooltip tooltip-success tooltip-right"

                  data-tip="Créneaux disponibles">

                  {{ availableSlots|length }}
                </span>
              {% else %}
                <span
                  class="badge badge-error badge-xs font-semibold ml-2 tooltip tooltip-error tooltip-right"

                  data-tip="Pas de créneau disponible">
                  0
                </span>
              {% endif %}
            {% endif %}

          </a>
        {% endfor %}
      </div>
      {# gradient opaque pour inciter à scroller sur Mobile #}
      <div
        class="tabs-gradient"></div>
    </div>


    {# Contenu de chaque tab avec animation #}
    {% for dateSession in dateSessions %}
      <div
        id="content-{{ loop.index }}"
        class="transform transition-all duration-300 ease-in-out {{ not loop.first ? 'hidden opacity-0' : 'opacity-100' }}">
        <div
          class="card bg-base-100 shadow-lg hover:shadow-xl transition-shadow duration-300">
          <div
            class="card-body">
            <h2
              class="card-title text-2xl flex items-center gap-2">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6 text-primary"
                fill="none"
                viewbox="0 0 24 24"
                stroke="currentColor">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>
              </svg>
              {{ dateSession.startTime|date('H:i') }}
              à
              {{ dateSession.endTime|date('H:i') }}
            </h2>
            <div
              class="overflow-x-auto">

              {% if filter == 'all' %}
                {# Afficher tous les créneaux #}
                {% include 'session/_session-table.html.twig' with {'dateSession': dateSession, 'eleves': eleves, 'filter': filter} only %}

              {% elseif filter == 'free' %}
                {# Affichage des créneaux libres #}
                {% set availableSlots = dateSession.slots|filter(slot => not slot.isBooked) %}
                {% if availableSlots|length > 0 %}

                  {% include 'session/_session-table.html.twig' with {'dateSession': dateSession, 'eleves': eleves, 'filter': filter} only %}

                {% else %}
                  <div
                    class="alert alert-warning shadow-lg">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      class="stroke-current shrink-0 h-6 w-6"
                      fill="none"
                      viewbox="0 0 24 24">
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/>
                    </svg>
                    <span>
                      Aucun créneau disponible pour cette date.
                    </span>
                  </div>
                {% endif %}

              {% else %}
                {# Affichage des créneaux réservés #}
                {% set bookedSlots = dateSession.slots|filter(slot => slot.isBooked) %}
                {% if bookedSlots|length > 0 %}

                  {% include 'session/_session-table.html.twig' with {'dateSession': dateSession, 'eleves': eleves, 'filter': filter} only %}

                {% else %}
                  <div
                    class="alert alert-warning shadow-lg">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      class="stroke-current shrink-0 h-6 w-6"
                      fill="none"
                      viewbox="0 0 24 24">
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>
                    <span>
                      Aucun créneau réservé pour cette date.
                    </span>
                  </div>
                {% endif %}
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  {% endblock %}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Les évènements à venir | Réserva'Classe
{% endblock %}

{% block title_h1 %}
  Toutes les évènements
{% endblock %}

{% block body %}

  <div
    class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 p-4">
    {% for session in sessions %}
      <div
        class="card bg-base-100 shadow-lg">
        <div
          class="card-body gap-8">
          <div>
            <div
              class="mb-2 md:text-center">
              <h2
                class="badge badge-md md:badge-xl badge-secondary mb-4">
                {{ session.label }}
              </h2>
            </div>
            <div
              class="mb-2">
              <span>
                Enseignant :
              </span>
              <span
                class="badge badge-sm md:badge-md badge-neutral badge-soft font-bold">

                {{ session.user.fullName|default('Enseignant inconnu') }}
              </span>
            </div>
            <div
              class="mb-[3rem]">
              <span>
                Créneaux disponibles :
              </span>
              {% set slots = session.availableSlots %}
              <span
                class="badge {{ slots.available > 0 ? 'badge-success' : 'badge-error' }} badge-sm md:badge-md  font-semibold ">


                {{ slots.available }}
                /
                {{ slots.total }}
              </span>
            </div>
            <div
              class="card-actions justify-end">
              {% if slots.available > 0 %}
                <a
                  href="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {{ path('session.show', { id: session.id, filter: 'free' }) }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "
                  class="btn btn-primary">

                  S'inscrire
                </a>
              {% else %}
                <button
                  class="btn btn-disabled"
                  disabled>
                  Complet
                </button>
              {% endif  %}

            </div>
          </div>
        </div>
      </div>
    {% endfor %}


  {% endblock %}